#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloSeed
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_LIBRARY_SEED")]
	public partial class LibrarySeedBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBL_USUARIO(TBL_USUARIO instance);
    partial void UpdateTBL_USUARIO(TBL_USUARIO instance);
    partial void DeleteTBL_USUARIO(TBL_USUARIO instance);
    partial void InsertTBL_AUTOR(TBL_AUTOR instance);
    partial void UpdateTBL_AUTOR(TBL_AUTOR instance);
    partial void DeleteTBL_AUTOR(TBL_AUTOR instance);
    partial void InsertTBL_CATEGORIA(TBL_CATEGORIA instance);
    partial void UpdateTBL_CATEGORIA(TBL_CATEGORIA instance);
    partial void DeleteTBL_CATEGORIA(TBL_CATEGORIA instance);
    partial void InsertTBL_EDITORIAL(TBL_EDITORIAL instance);
    partial void UpdateTBL_EDITORIAL(TBL_EDITORIAL instance);
    partial void DeleteTBL_EDITORIAL(TBL_EDITORIAL instance);
    partial void InsertTBL_INVENTARIO(TBL_INVENTARIO instance);
    partial void UpdateTBL_INVENTARIO(TBL_INVENTARIO instance);
    partial void DeleteTBL_INVENTARIO(TBL_INVENTARIO instance);
    partial void InsertTBL_LIBRO(TBL_LIBRO instance);
    partial void UpdateTBL_LIBRO(TBL_LIBRO instance);
    partial void DeleteTBL_LIBRO(TBL_LIBRO instance);
    partial void InsertTBL_PRESTAMO(TBL_PRESTAMO instance);
    partial void UpdateTBL_PRESTAMO(TBL_PRESTAMO instance);
    partial void DeleteTBL_PRESTAMO(TBL_PRESTAMO instance);
    partial void InsertTBL_tipousuario(TBL_tipousuario instance);
    partial void UpdateTBL_tipousuario(TBL_tipousuario instance);
    partial void DeleteTBL_tipousuario(TBL_tipousuario instance);
    #endregion
		
		public LibrarySeedBDDataContext() : 
				base(global::ModeloSeed.Properties.Settings.Default.BD_LIBRARY_SEEDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LibrarySeedBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibrarySeedBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibrarySeedBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibrarySeedBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this.GetTable<TBL_USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<EditorialesYSusLibros> EditorialesYSusLibros
		{
			get
			{
				return this.GetTable<EditorialesYSusLibros>();
			}
		}
		
		public System.Data.Linq.Table<TBL_AUTOR> TBL_AUTOR
		{
			get
			{
				return this.GetTable<TBL_AUTOR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CATEGORIA> TBL_CATEGORIA
		{
			get
			{
				return this.GetTable<TBL_CATEGORIA>();
			}
		}
		
		public System.Data.Linq.Table<TBL_EDITORIAL> TBL_EDITORIAL
		{
			get
			{
				return this.GetTable<TBL_EDITORIAL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_GESTION_PRESTAMO> TBL_GESTION_PRESTAMO
		{
			get
			{
				return this.GetTable<TBL_GESTION_PRESTAMO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_INVENTARIO> TBL_INVENTARIO
		{
			get
			{
				return this.GetTable<TBL_INVENTARIO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_LIBRO> TBL_LIBRO
		{
			get
			{
				return this.GetTable<TBL_LIBRO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PRESTAMO> TBL_PRESTAMO
		{
			get
			{
				return this.GetTable<TBL_PRESTAMO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_tipousuario> TBL_tipousuario
		{
			get
			{
				return this.GetTable<TBL_tipousuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USUARIO")]
	public partial class TBL_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cedula;
		
		private string _Nom_usuario;
		
		private string _Apell_usuario;
		
		private decimal _Telef_usuario;
		
		private string _Dirrec_usuario;
		
		private string _Correo_usuario;
		
		private int _ID_tipousuario;
		
		private EntitySet<TBL_PRESTAMO> _TBL_PRESTAMO;
		
		private EntityRef<TBL_tipousuario> _TBL_tipousuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNom_usuarioChanging(string value);
    partial void OnNom_usuarioChanged();
    partial void OnApell_usuarioChanging(string value);
    partial void OnApell_usuarioChanged();
    partial void OnTelef_usuarioChanging(decimal value);
    partial void OnTelef_usuarioChanged();
    partial void OnDirrec_usuarioChanging(string value);
    partial void OnDirrec_usuarioChanged();
    partial void OnCorreo_usuarioChanging(string value);
    partial void OnCorreo_usuarioChanged();
    partial void OnID_tipousuarioChanging(int value);
    partial void OnID_tipousuarioChanged();
    #endregion
		
		public TBL_USUARIO()
		{
			this._TBL_PRESTAMO = new EntitySet<TBL_PRESTAMO>(new Action<TBL_PRESTAMO>(this.attach_TBL_PRESTAMO), new Action<TBL_PRESTAMO>(this.detach_TBL_PRESTAMO));
			this._TBL_tipousuario = default(EntityRef<TBL_tipousuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(70) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nom_usuario
		{
			get
			{
				return this._Nom_usuario;
			}
			set
			{
				if ((this._Nom_usuario != value))
				{
					this.OnNom_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Nom_usuario = value;
					this.SendPropertyChanged("Nom_usuario");
					this.OnNom_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apell_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apell_usuario
		{
			get
			{
				return this._Apell_usuario;
			}
			set
			{
				if ((this._Apell_usuario != value))
				{
					this.OnApell_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Apell_usuario = value;
					this.SendPropertyChanged("Apell_usuario");
					this.OnApell_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telef_usuario", DbType="Decimal(18,0) NOT NULL")]
		public decimal Telef_usuario
		{
			get
			{
				return this._Telef_usuario;
			}
			set
			{
				if ((this._Telef_usuario != value))
				{
					this.OnTelef_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Telef_usuario = value;
					this.SendPropertyChanged("Telef_usuario");
					this.OnTelef_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirrec_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dirrec_usuario
		{
			get
			{
				return this._Dirrec_usuario;
			}
			set
			{
				if ((this._Dirrec_usuario != value))
				{
					this.OnDirrec_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Dirrec_usuario = value;
					this.SendPropertyChanged("Dirrec_usuario");
					this.OnDirrec_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo_usuario
		{
			get
			{
				return this._Correo_usuario;
			}
			set
			{
				if ((this._Correo_usuario != value))
				{
					this.OnCorreo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._Correo_usuario = value;
					this.SendPropertyChanged("Correo_usuario");
					this.OnCorreo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_tipousuario", DbType="Int NOT NULL")]
		public int ID_tipousuario
		{
			get
			{
				return this._ID_tipousuario;
			}
			set
			{
				if ((this._ID_tipousuario != value))
				{
					if (this._TBL_tipousuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_tipousuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_tipousuario = value;
					this.SendPropertyChanged("ID_tipousuario");
					this.OnID_tipousuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_USUARIO_TBL_PRESTAMO", Storage="_TBL_PRESTAMO", ThisKey="Cedula", OtherKey="Cedula")]
		public EntitySet<TBL_PRESTAMO> TBL_PRESTAMO
		{
			get
			{
				return this._TBL_PRESTAMO;
			}
			set
			{
				this._TBL_PRESTAMO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_tipousuario_TBL_USUARIO", Storage="_TBL_tipousuario", ThisKey="ID_tipousuario", OtherKey="ID_tipousuario", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBL_tipousuario TBL_tipousuario
		{
			get
			{
				return this._TBL_tipousuario.Entity;
			}
			set
			{
				TBL_tipousuario previousValue = this._TBL_tipousuario.Entity;
				if (((previousValue != value) 
							|| (this._TBL_tipousuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_tipousuario.Entity = null;
						previousValue.TBL_USUARIO.Remove(this);
					}
					this._TBL_tipousuario.Entity = value;
					if ((value != null))
					{
						value.TBL_USUARIO.Add(this);
						this._ID_tipousuario = value.ID_tipousuario;
					}
					else
					{
						this._ID_tipousuario = default(int);
					}
					this.SendPropertyChanged("TBL_tipousuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PRESTAMO(TBL_PRESTAMO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_USUARIO = this;
		}
		
		private void detach_TBL_PRESTAMO(TBL_PRESTAMO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_USUARIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EditorialesYSusLibros")]
	public partial class EditorialesYSusLibros
	{
		
		private int _ID_edit;
		
		private string _ID_libro;
		
		public EditorialesYSusLibros()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_edit", DbType="Int NOT NULL")]
		public int ID_edit
		{
			get
			{
				return this._ID_edit;
			}
			set
			{
				if ((this._ID_edit != value))
				{
					this._ID_edit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_libro", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ID_libro
		{
			get
			{
				return this._ID_libro;
			}
			set
			{
				if ((this._ID_libro != value))
				{
					this._ID_libro = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_AUTOR")]
	public partial class TBL_AUTOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_aut;
		
		private string _Nacionalidad;
		
		private string _Nomb_aut;
		
		private string _Apell_aut;
		
		private EntitySet<TBL_LIBRO> _TBL_LIBRO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_autChanging(int value);
    partial void OnID_autChanged();
    partial void OnNacionalidadChanging(string value);
    partial void OnNacionalidadChanged();
    partial void OnNomb_autChanging(string value);
    partial void OnNomb_autChanged();
    partial void OnApell_autChanging(string value);
    partial void OnApell_autChanged();
    #endregion
		
		public TBL_AUTOR()
		{
			this._TBL_LIBRO = new EntitySet<TBL_LIBRO>(new Action<TBL_LIBRO>(this.attach_TBL_LIBRO), new Action<TBL_LIBRO>(this.detach_TBL_LIBRO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_aut", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_aut
		{
			get
			{
				return this._ID_aut;
			}
			set
			{
				if ((this._ID_aut != value))
				{
					this.OnID_autChanging(value);
					this.SendPropertyChanging();
					this._ID_aut = value;
					this.SendPropertyChanged("ID_aut");
					this.OnID_autChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nacionalidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nacionalidad
		{
			get
			{
				return this._Nacionalidad;
			}
			set
			{
				if ((this._Nacionalidad != value))
				{
					this.OnNacionalidadChanging(value);
					this.SendPropertyChanging();
					this._Nacionalidad = value;
					this.SendPropertyChanged("Nacionalidad");
					this.OnNacionalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nomb_aut", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nomb_aut
		{
			get
			{
				return this._Nomb_aut;
			}
			set
			{
				if ((this._Nomb_aut != value))
				{
					this.OnNomb_autChanging(value);
					this.SendPropertyChanging();
					this._Nomb_aut = value;
					this.SendPropertyChanged("Nomb_aut");
					this.OnNomb_autChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apell_aut", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Apell_aut
		{
			get
			{
				return this._Apell_aut;
			}
			set
			{
				if ((this._Apell_aut != value))
				{
					this.OnApell_autChanging(value);
					this.SendPropertyChanging();
					this._Apell_aut = value;
					this.SendPropertyChanged("Apell_aut");
					this.OnApell_autChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_AUTOR_TBL_LIBRO", Storage="_TBL_LIBRO", ThisKey="ID_aut", OtherKey="ID_aut")]
		public EntitySet<TBL_LIBRO> TBL_LIBRO
		{
			get
			{
				return this._TBL_LIBRO;
			}
			set
			{
				this._TBL_LIBRO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_LIBRO(TBL_LIBRO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_AUTOR = this;
		}
		
		private void detach_TBL_LIBRO(TBL_LIBRO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_AUTOR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CATEGORIA")]
	public partial class TBL_CATEGORIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_categoria;
		
		private string _Nombre_Cat;
		
		private string _Ref_Cat;
		
		private EntitySet<TBL_LIBRO> _TBL_LIBRO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_categoriaChanging(int value);
    partial void OnID_categoriaChanged();
    partial void OnNombre_CatChanging(string value);
    partial void OnNombre_CatChanged();
    partial void OnRef_CatChanging(string value);
    partial void OnRef_CatChanged();
    #endregion
		
		public TBL_CATEGORIA()
		{
			this._TBL_LIBRO = new EntitySet<TBL_LIBRO>(new Action<TBL_LIBRO>(this.attach_TBL_LIBRO), new Action<TBL_LIBRO>(this.detach_TBL_LIBRO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_categoria
		{
			get
			{
				return this._ID_categoria;
			}
			set
			{
				if ((this._ID_categoria != value))
				{
					this.OnID_categoriaChanging(value);
					this.SendPropertyChanging();
					this._ID_categoria = value;
					this.SendPropertyChanged("ID_categoria");
					this.OnID_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Cat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre_Cat
		{
			get
			{
				return this._Nombre_Cat;
			}
			set
			{
				if ((this._Nombre_Cat != value))
				{
					this.OnNombre_CatChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Cat = value;
					this.SendPropertyChanged("Nombre_Cat");
					this.OnNombre_CatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ref_Cat", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Ref_Cat
		{
			get
			{
				return this._Ref_Cat;
			}
			set
			{
				if ((this._Ref_Cat != value))
				{
					this.OnRef_CatChanging(value);
					this.SendPropertyChanging();
					this._Ref_Cat = value;
					this.SendPropertyChanged("Ref_Cat");
					this.OnRef_CatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_CATEGORIA_TBL_LIBRO", Storage="_TBL_LIBRO", ThisKey="ID_categoria", OtherKey="ID_categoria")]
		public EntitySet<TBL_LIBRO> TBL_LIBRO
		{
			get
			{
				return this._TBL_LIBRO;
			}
			set
			{
				this._TBL_LIBRO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_LIBRO(TBL_LIBRO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_CATEGORIA = this;
		}
		
		private void detach_TBL_LIBRO(TBL_LIBRO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_CATEGORIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_EDITORIAL")]
	public partial class TBL_EDITORIAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_edit;
		
		private string _Nomb_edit;
		
		private EntitySet<TBL_LIBRO> _TBL_LIBRO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_editChanging(int value);
    partial void OnID_editChanged();
    partial void OnNomb_editChanging(string value);
    partial void OnNomb_editChanged();
    #endregion
		
		public TBL_EDITORIAL()
		{
			this._TBL_LIBRO = new EntitySet<TBL_LIBRO>(new Action<TBL_LIBRO>(this.attach_TBL_LIBRO), new Action<TBL_LIBRO>(this.detach_TBL_LIBRO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_edit", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_edit
		{
			get
			{
				return this._ID_edit;
			}
			set
			{
				if ((this._ID_edit != value))
				{
					this.OnID_editChanging(value);
					this.SendPropertyChanging();
					this._ID_edit = value;
					this.SendPropertyChanged("ID_edit");
					this.OnID_editChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nomb_edit", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nomb_edit
		{
			get
			{
				return this._Nomb_edit;
			}
			set
			{
				if ((this._Nomb_edit != value))
				{
					this.OnNomb_editChanging(value);
					this.SendPropertyChanging();
					this._Nomb_edit = value;
					this.SendPropertyChanged("Nomb_edit");
					this.OnNomb_editChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_EDITORIAL_TBL_LIBRO", Storage="_TBL_LIBRO", ThisKey="ID_edit", OtherKey="ID_edit")]
		public EntitySet<TBL_LIBRO> TBL_LIBRO
		{
			get
			{
				return this._TBL_LIBRO;
			}
			set
			{
				this._TBL_LIBRO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_LIBRO(TBL_LIBRO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_EDITORIAL = this;
		}
		
		private void detach_TBL_LIBRO(TBL_LIBRO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_EDITORIAL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_GESTION_PRESTAMO")]
	public partial class TBL_GESTION_PRESTAMO
	{
		
		private string _ID_libro;
		
		private int _ID_prestamo;
		
		public TBL_GESTION_PRESTAMO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_libro", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ID_libro
		{
			get
			{
				return this._ID_libro;
			}
			set
			{
				if ((this._ID_libro != value))
				{
					this._ID_libro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_prestamo", DbType="Int NOT NULL")]
		public int ID_prestamo
		{
			get
			{
				return this._ID_prestamo;
			}
			set
			{
				if ((this._ID_prestamo != value))
				{
					this._ID_prestamo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_INVENTARIO")]
	public partial class TBL_INVENTARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_inventario;
		
		private int _ID_libro;
		
		private int _Existencia_total;
		
		private int _Libro_prestamo;
		
		private int _Existencia;
		
		private EntitySet<TBL_PRESTAMO> _TBL_PRESTAMO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_inventarioChanging(int value);
    partial void OnID_inventarioChanged();
    partial void OnID_libroChanging(int value);
    partial void OnID_libroChanged();
    partial void OnExistencia_totalChanging(int value);
    partial void OnExistencia_totalChanged();
    partial void OnLibro_prestamoChanging(int value);
    partial void OnLibro_prestamoChanged();
    partial void OnExistenciaChanging(int value);
    partial void OnExistenciaChanged();
    #endregion
		
		public TBL_INVENTARIO()
		{
			this._TBL_PRESTAMO = new EntitySet<TBL_PRESTAMO>(new Action<TBL_PRESTAMO>(this.attach_TBL_PRESTAMO), new Action<TBL_PRESTAMO>(this.detach_TBL_PRESTAMO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_inventario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_inventario
		{
			get
			{
				return this._ID_inventario;
			}
			set
			{
				if ((this._ID_inventario != value))
				{
					this.OnID_inventarioChanging(value);
					this.SendPropertyChanging();
					this._ID_inventario = value;
					this.SendPropertyChanged("ID_inventario");
					this.OnID_inventarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_libro", DbType="Int NOT NULL")]
		public int ID_libro
		{
			get
			{
				return this._ID_libro;
			}
			set
			{
				if ((this._ID_libro != value))
				{
					this.OnID_libroChanging(value);
					this.SendPropertyChanging();
					this._ID_libro = value;
					this.SendPropertyChanged("ID_libro");
					this.OnID_libroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencia_total", DbType="Int NOT NULL")]
		public int Existencia_total
		{
			get
			{
				return this._Existencia_total;
			}
			set
			{
				if ((this._Existencia_total != value))
				{
					this.OnExistencia_totalChanging(value);
					this.SendPropertyChanging();
					this._Existencia_total = value;
					this.SendPropertyChanged("Existencia_total");
					this.OnExistencia_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Libro_prestamo", DbType="Int NOT NULL")]
		public int Libro_prestamo
		{
			get
			{
				return this._Libro_prestamo;
			}
			set
			{
				if ((this._Libro_prestamo != value))
				{
					this.OnLibro_prestamoChanging(value);
					this.SendPropertyChanging();
					this._Libro_prestamo = value;
					this.SendPropertyChanged("Libro_prestamo");
					this.OnLibro_prestamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencia", DbType="Int NOT NULL")]
		public int Existencia
		{
			get
			{
				return this._Existencia;
			}
			set
			{
				if ((this._Existencia != value))
				{
					this.OnExistenciaChanging(value);
					this.SendPropertyChanging();
					this._Existencia = value;
					this.SendPropertyChanged("Existencia");
					this.OnExistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_INVENTARIO_TBL_PRESTAMO", Storage="_TBL_PRESTAMO", ThisKey="ID_inventario", OtherKey="ID_inventario")]
		public EntitySet<TBL_PRESTAMO> TBL_PRESTAMO
		{
			get
			{
				return this._TBL_PRESTAMO;
			}
			set
			{
				this._TBL_PRESTAMO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_PRESTAMO(TBL_PRESTAMO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_INVENTARIO = this;
		}
		
		private void detach_TBL_PRESTAMO(TBL_PRESTAMO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_INVENTARIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_LIBRO")]
	public partial class TBL_LIBRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_libro;
		
		private int _ID_categoria;
		
		private int _ID_aut;
		
		private string _Titulo_libro;
		
		private string _Idioma_libro;
		
		private int _ID_edit;
		
		private bool _Existencia;
		
		private EntityRef<TBL_AUTOR> _TBL_AUTOR;
		
		private EntityRef<TBL_CATEGORIA> _TBL_CATEGORIA;
		
		private EntityRef<TBL_EDITORIAL> _TBL_EDITORIAL;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_libroChanging(string value);
    partial void OnID_libroChanged();
    partial void OnID_categoriaChanging(int value);
    partial void OnID_categoriaChanged();
    partial void OnID_autChanging(int value);
    partial void OnID_autChanged();
    partial void OnTitulo_libroChanging(string value);
    partial void OnTitulo_libroChanged();
    partial void OnIdioma_libroChanging(string value);
    partial void OnIdioma_libroChanged();
    partial void OnID_editChanging(int value);
    partial void OnID_editChanged();
    partial void OnExistenciaChanging(bool value);
    partial void OnExistenciaChanged();
    #endregion
		
		public TBL_LIBRO()
		{
			this._TBL_AUTOR = default(EntityRef<TBL_AUTOR>);
			this._TBL_CATEGORIA = default(EntityRef<TBL_CATEGORIA>);
			this._TBL_EDITORIAL = default(EntityRef<TBL_EDITORIAL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_libro", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_libro
		{
			get
			{
				return this._ID_libro;
			}
			set
			{
				if ((this._ID_libro != value))
				{
					this.OnID_libroChanging(value);
					this.SendPropertyChanging();
					this._ID_libro = value;
					this.SendPropertyChanged("ID_libro");
					this.OnID_libroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_categoria", DbType="Int NOT NULL")]
		public int ID_categoria
		{
			get
			{
				return this._ID_categoria;
			}
			set
			{
				if ((this._ID_categoria != value))
				{
					if (this._TBL_CATEGORIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_categoriaChanging(value);
					this.SendPropertyChanging();
					this._ID_categoria = value;
					this.SendPropertyChanged("ID_categoria");
					this.OnID_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_aut", DbType="Int NOT NULL")]
		public int ID_aut
		{
			get
			{
				return this._ID_aut;
			}
			set
			{
				if ((this._ID_aut != value))
				{
					if (this._TBL_AUTOR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_autChanging(value);
					this.SendPropertyChanging();
					this._ID_aut = value;
					this.SendPropertyChanged("ID_aut");
					this.OnID_autChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo_libro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Titulo_libro
		{
			get
			{
				return this._Titulo_libro;
			}
			set
			{
				if ((this._Titulo_libro != value))
				{
					this.OnTitulo_libroChanging(value);
					this.SendPropertyChanging();
					this._Titulo_libro = value;
					this.SendPropertyChanged("Titulo_libro");
					this.OnTitulo_libroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idioma_libro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Idioma_libro
		{
			get
			{
				return this._Idioma_libro;
			}
			set
			{
				if ((this._Idioma_libro != value))
				{
					this.OnIdioma_libroChanging(value);
					this.SendPropertyChanging();
					this._Idioma_libro = value;
					this.SendPropertyChanged("Idioma_libro");
					this.OnIdioma_libroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_edit", DbType="Int NOT NULL")]
		public int ID_edit
		{
			get
			{
				return this._ID_edit;
			}
			set
			{
				if ((this._ID_edit != value))
				{
					if (this._TBL_EDITORIAL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_editChanging(value);
					this.SendPropertyChanging();
					this._ID_edit = value;
					this.SendPropertyChanged("ID_edit");
					this.OnID_editChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencia", DbType="Bit NOT NULL")]
		public bool Existencia
		{
			get
			{
				return this._Existencia;
			}
			set
			{
				if ((this._Existencia != value))
				{
					this.OnExistenciaChanging(value);
					this.SendPropertyChanging();
					this._Existencia = value;
					this.SendPropertyChanged("Existencia");
					this.OnExistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_AUTOR_TBL_LIBRO", Storage="_TBL_AUTOR", ThisKey="ID_aut", OtherKey="ID_aut", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBL_AUTOR TBL_AUTOR
		{
			get
			{
				return this._TBL_AUTOR.Entity;
			}
			set
			{
				TBL_AUTOR previousValue = this._TBL_AUTOR.Entity;
				if (((previousValue != value) 
							|| (this._TBL_AUTOR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_AUTOR.Entity = null;
						previousValue.TBL_LIBRO.Remove(this);
					}
					this._TBL_AUTOR.Entity = value;
					if ((value != null))
					{
						value.TBL_LIBRO.Add(this);
						this._ID_aut = value.ID_aut;
					}
					else
					{
						this._ID_aut = default(int);
					}
					this.SendPropertyChanged("TBL_AUTOR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_CATEGORIA_TBL_LIBRO", Storage="_TBL_CATEGORIA", ThisKey="ID_categoria", OtherKey="ID_categoria", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBL_CATEGORIA TBL_CATEGORIA
		{
			get
			{
				return this._TBL_CATEGORIA.Entity;
			}
			set
			{
				TBL_CATEGORIA previousValue = this._TBL_CATEGORIA.Entity;
				if (((previousValue != value) 
							|| (this._TBL_CATEGORIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_CATEGORIA.Entity = null;
						previousValue.TBL_LIBRO.Remove(this);
					}
					this._TBL_CATEGORIA.Entity = value;
					if ((value != null))
					{
						value.TBL_LIBRO.Add(this);
						this._ID_categoria = value.ID_categoria;
					}
					else
					{
						this._ID_categoria = default(int);
					}
					this.SendPropertyChanged("TBL_CATEGORIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_EDITORIAL_TBL_LIBRO", Storage="_TBL_EDITORIAL", ThisKey="ID_edit", OtherKey="ID_edit", IsForeignKey=true)]
		public TBL_EDITORIAL TBL_EDITORIAL
		{
			get
			{
				return this._TBL_EDITORIAL.Entity;
			}
			set
			{
				TBL_EDITORIAL previousValue = this._TBL_EDITORIAL.Entity;
				if (((previousValue != value) 
							|| (this._TBL_EDITORIAL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_EDITORIAL.Entity = null;
						previousValue.TBL_LIBRO.Remove(this);
					}
					this._TBL_EDITORIAL.Entity = value;
					if ((value != null))
					{
						value.TBL_LIBRO.Add(this);
						this._ID_edit = value.ID_edit;
					}
					else
					{
						this._ID_edit = default(int);
					}
					this.SendPropertyChanged("TBL_EDITORIAL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PRESTAMO")]
	public partial class TBL_PRESTAMO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_prestamo;
		
		private string _Cedula;
		
		private System.DateTime _Fecha_devolucion;
		
		private System.DateTime _Fecha_entrega;
		
		private bool _Entrega;
		
		private int _ID_inventario;
		
		private EntityRef<TBL_INVENTARIO> _TBL_INVENTARIO;
		
		private EntityRef<TBL_USUARIO> _TBL_USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_prestamoChanging(int value);
    partial void OnID_prestamoChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnFecha_devolucionChanging(System.DateTime value);
    partial void OnFecha_devolucionChanged();
    partial void OnFecha_entregaChanging(System.DateTime value);
    partial void OnFecha_entregaChanged();
    partial void OnEntregaChanging(bool value);
    partial void OnEntregaChanged();
    partial void OnID_inventarioChanging(int value);
    partial void OnID_inventarioChanged();
    #endregion
		
		public TBL_PRESTAMO()
		{
			this._TBL_INVENTARIO = default(EntityRef<TBL_INVENTARIO>);
			this._TBL_USUARIO = default(EntityRef<TBL_USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_prestamo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_prestamo
		{
			get
			{
				return this._ID_prestamo;
			}
			set
			{
				if ((this._ID_prestamo != value))
				{
					this.OnID_prestamoChanging(value);
					this.SendPropertyChanging();
					this._ID_prestamo = value;
					this.SendPropertyChanged("ID_prestamo");
					this.OnID_prestamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					if (this._TBL_USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_devolucion", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_devolucion
		{
			get
			{
				return this._Fecha_devolucion;
			}
			set
			{
				if ((this._Fecha_devolucion != value))
				{
					this.OnFecha_devolucionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_devolucion = value;
					this.SendPropertyChanged("Fecha_devolucion");
					this.OnFecha_devolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_entrega", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_entrega
		{
			get
			{
				return this._Fecha_entrega;
			}
			set
			{
				if ((this._Fecha_entrega != value))
				{
					this.OnFecha_entregaChanging(value);
					this.SendPropertyChanging();
					this._Fecha_entrega = value;
					this.SendPropertyChanged("Fecha_entrega");
					this.OnFecha_entregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrega", DbType="Bit NOT NULL")]
		public bool Entrega
		{
			get
			{
				return this._Entrega;
			}
			set
			{
				if ((this._Entrega != value))
				{
					this.OnEntregaChanging(value);
					this.SendPropertyChanging();
					this._Entrega = value;
					this.SendPropertyChanged("Entrega");
					this.OnEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_inventario", DbType="Int NOT NULL")]
		public int ID_inventario
		{
			get
			{
				return this._ID_inventario;
			}
			set
			{
				if ((this._ID_inventario != value))
				{
					if (this._TBL_INVENTARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_inventarioChanging(value);
					this.SendPropertyChanging();
					this._ID_inventario = value;
					this.SendPropertyChanged("ID_inventario");
					this.OnID_inventarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_INVENTARIO_TBL_PRESTAMO", Storage="_TBL_INVENTARIO", ThisKey="ID_inventario", OtherKey="ID_inventario", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBL_INVENTARIO TBL_INVENTARIO
		{
			get
			{
				return this._TBL_INVENTARIO.Entity;
			}
			set
			{
				TBL_INVENTARIO previousValue = this._TBL_INVENTARIO.Entity;
				if (((previousValue != value) 
							|| (this._TBL_INVENTARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_INVENTARIO.Entity = null;
						previousValue.TBL_PRESTAMO.Remove(this);
					}
					this._TBL_INVENTARIO.Entity = value;
					if ((value != null))
					{
						value.TBL_PRESTAMO.Add(this);
						this._ID_inventario = value.ID_inventario;
					}
					else
					{
						this._ID_inventario = default(int);
					}
					this.SendPropertyChanged("TBL_INVENTARIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_USUARIO_TBL_PRESTAMO", Storage="_TBL_USUARIO", ThisKey="Cedula", OtherKey="Cedula", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TBL_USUARIO TBL_USUARIO
		{
			get
			{
				return this._TBL_USUARIO.Entity;
			}
			set
			{
				TBL_USUARIO previousValue = this._TBL_USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._TBL_USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_USUARIO.Entity = null;
						previousValue.TBL_PRESTAMO.Remove(this);
					}
					this._TBL_USUARIO.Entity = value;
					if ((value != null))
					{
						value.TBL_PRESTAMO.Add(this);
						this._Cedula = value.Cedula;
					}
					else
					{
						this._Cedula = default(string);
					}
					this.SendPropertyChanged("TBL_USUARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_tipousuario")]
	public partial class TBL_tipousuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_tipousuario;
		
		private string _Tipo_Usuario;
		
		private EntitySet<TBL_USUARIO> _TBL_USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_tipousuarioChanging(int value);
    partial void OnID_tipousuarioChanged();
    partial void OnTipo_UsuarioChanging(string value);
    partial void OnTipo_UsuarioChanged();
    #endregion
		
		public TBL_tipousuario()
		{
			this._TBL_USUARIO = new EntitySet<TBL_USUARIO>(new Action<TBL_USUARIO>(this.attach_TBL_USUARIO), new Action<TBL_USUARIO>(this.detach_TBL_USUARIO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_tipousuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_tipousuario
		{
			get
			{
				return this._ID_tipousuario;
			}
			set
			{
				if ((this._ID_tipousuario != value))
				{
					this.OnID_tipousuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_tipousuario = value;
					this.SendPropertyChanged("ID_tipousuario");
					this.OnID_tipousuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_Usuario", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Tipo_Usuario
		{
			get
			{
				return this._Tipo_Usuario;
			}
			set
			{
				if ((this._Tipo_Usuario != value))
				{
					this.OnTipo_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._Tipo_Usuario = value;
					this.SendPropertyChanged("Tipo_Usuario");
					this.OnTipo_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_tipousuario_TBL_USUARIO", Storage="_TBL_USUARIO", ThisKey="ID_tipousuario", OtherKey="ID_tipousuario")]
		public EntitySet<TBL_USUARIO> TBL_USUARIO
		{
			get
			{
				return this._TBL_USUARIO;
			}
			set
			{
				this._TBL_USUARIO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_USUARIO(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_tipousuario = this;
		}
		
		private void detach_TBL_USUARIO(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_tipousuario = null;
		}
	}
}
#pragma warning restore 1591
